// generated by go generate; DO NOT EDIT

package main

import (
	"html/template"
)

var (
	adminTmpl       = template.Must(template.New("adminTmpl").Funcs(fns).Parse(baseTemplate + navTemplate + toolbarTemplate + adminTemplate))
	aliasNewTmpl    = template.Must(template.New("aliasNewTmpl").Funcs(fns).Parse(baseTemplate + navTemplate + alias_newTemplate))
	aliasSearchTmpl = template.Must(template.New("aliasSearchTmpl").Funcs(fns).Parse(baseTemplate + navTemplate + alias_searchTemplate))
	aliasTmpl       = template.Must(template.New("aliasTmpl").Funcs(fns).Parse(baseTemplate + navTemplate + aliasTemplate))
	loginTmpl       = template.Must(template.New("loginTmpl").Funcs(fns).Parse(baseTemplate + loginTemplate))
	submitTmpl      = template.Must(template.New("submitTmpl").Funcs(fns).Parse(baseTemplate + navTemplate + submitTemplate))
	suggestionTmpl  = template.Must(template.New("suggestionTmpl").Funcs(fns).Parse(baseTemplate + navTemplate + suggestionTemplate))
)

const (
	adminTemplate = `
{{define "content"}}
{{ range $k, $v := .Data }}
	<div class="suggestion">
		<span>{{$v.FmtCreated}} by <a href="/user/{{$v.Username}}">{{$v.Username}}</a></span>
		<form method="post" action="/suggest/admin/delete">
			<input type="hidden" name="username" value="{{$v.Username}}">
			<input type="hidden" name="id" value="{{$v.ID}}">
			<input type="submit" value="Delete">
		</form>
		<textarea cols="80" readonly>{{$v.Text}}</textarea>
	</div>
{{ end }}
{{end}}
`
	aliasTemplate = `
{{define "css"}}
  <style>
    .alias-form {
      padding: 0.5em;
      line-height: 200%;
    }
    .alias-form submit {
      display: inline;
      font-size: 120%;
    }
    .alias-form input {
      font-size: 120%;
    }
  </style>
{{ end }}
{{define "content"}}
  <div class="alias-form">
    <form method="post" action="/suggest/alias/new/submit">
      <input type="text" name="old" placeholder="Old Tag" required pattern="^\S+$" title="tags cannot contain spaces" >
      <input type="text" name="new" placeholder="New Tag" required pattern="^\S+$" title="tags cannot contain spaces" >
      <input type="text" name="comment" placeholder="Comment (Optional)">
      <input type="submit" value="Suggest New Alias">
    </form>
  </div>
{{ end }}
`
	alias_newTemplate = `
{{define "css"}}
  <style>
    .alias-form {
      padding: 0.5em;
      line-height: 200%;
    }
    .alias-form submit {
      display: inline;
      font-size: 120%;
    }
    .alias-form input {
      font-size: 120%;
    }
  </style>
{{ end }}
{{define "content"}}
  <div class="alias-form">
    <form method="post" action="/suggest/alias/new/submit">
      <input type="text" name="old" placeholder="Old Tag" required pattern="^\S+$" title="tags cannot contain spaces" >
      <input type="text" name="new" placeholder="New Tag" required pattern="^\S+$" title="tags cannot contain spaces" >
      <input type="text" name="comment" placeholder="Comment (Optional)">
      <input type="submit" value="Suggest New Alias">
    </form>
  </div>
{{ end }}
`
	alias_searchTemplate = `
{{define "css"}}
  <style>
    .alias input {
      font-size: 120%;
    }
    .alias label {
      font-size: 120%;
    }
    .alias form {
      display: inline;
    }
    .alias {
      padding: 0.5em;
      border-top: 1px #ebebeb solid;
      border-bottom: 1px #ebebeb solid;
      border-left: 0.3em #006FFA solid;
      border-top-left-radius: 0.3em;
      border-bottom-left-radius: 0.3em;
      line-height: 200%;
    }
    .alias:nth-of-type(even) {
      background: #f6f6f6;
    }
    .alias-span {
      padding: 0.5em;
      font-size: 120%;
      display: block;
    }
    .alias-body {
      padding: 0.5em;
    }
    .alias-body label{
      padding-right: 0.5em;
    }
    .alias-body-field {
      display: inline-block;
      padding: 0.5em;
    }
    .alias-body-field label {
      display: inline-block;
      width: 5em;
      min-width:5em;
    }
    .alias-body-field.alias-body-field-tag input {
      display: inline-block;
      /*width: 6em;*/
      width: 15em;
    }
    .alias-body-field.alias-body-field-comment input {
      display: inline-block;
      width: 15em;
    }

    .alias-table {
      width: 100%;
      border-collapse: collapse;
    }
    table, td, th {
      border: 1px solid #ddd;
    }
    td, th {
      padding: 0.5em;
    }
    .alias-table-body tr:nth-child(odd) {
      background: #f9f9f9;
    }
    .status {
      width: 5px;
      padding: 0;
      margin: 0;
      /*border: 0px;*/
    }
    .status-new {
      background-color: #006ffa;
      /*background-color: #1b809e; bootstrap */
    }
    .status-rejected {
      /* background-color: #ce4844; bootstrap */
      background-color: #fa0c00;
    }
    .status-approved {
      /*background-color: #449d44; bootstrap */
      background-color: #70fa00;
    }
    .center {
      text-align: center;
    }

  </style>
{{ end }}
{{define "content"}}
  <div class="toolbar">
    <form method="get" action="/suggest/alias">
      <input type="text" name="username" placeholder="Username">
      <input type="text" name="comment" placeholder="Comment">
      <label for="order">Order By</label>
      <select id="order" name="order">
        <option value="dd">Date Desc</option>
        <option value="da">Date Asc</option>
        <option value="ud">Username Desc</option>
        <option value="ua">Username Asc</option>
      </select>
      <button type="submit">Search</button>
      <input type="reset" value="Reset">
    <a href="/suggest/alias/new">New</a>
    </form>
  </div>

  <table class="alias-table">
    <thead>
      <tr>
        <th class="status"></th>
        <th>Alias</th>
        <th>Comment</th>
        <th>Submitter</th>
        <th>Submitted At</th>
      </tr>
    </thead>
    <tbody class="alias-table-body">
      {{range .Data}}
        <tr>
		<td class="
		status
		{{if .Status.IsNew }}status-new{{end}}
		{{if eq .Status 1}}status-approved{{end}}
		{{if eq .Status 2}}status-rejected{{end}}"></td>
          <td><a class="alias-link" href="/suggest/alias/{{.ID}}">{{.Old}} &rarr; {{.New}}</a></td>
	  <td>{{.Comment}}</td>
	  <td class="center"><a href="/user/{{.Username}}">{{.Username}}</a></td>
	  <td class="center"><time>{{.FmtCreated}}</time></td>
	</tr>
      {{end}}
    </tbody>
  </table>

  {{ range .Data }}
    <div class="alias">
      <h2 class="alias-span">{{.Old}} &rarr; {{.New}}</h2>
      <span style="float:right"><time>{{.FmtCreated}}</time> by <a href="/user/{{.Username}}">{{.Username}}</a></span>
      <!-- ><span>{{.FmtCreated}} by <a href="/user/{{.Username}}">{{.Username}}</a></span> -->
      <span class="alias-span">Submitted At: {{.FmtCreated}}</span>
      {{if .Comment}}<span class="alias-span">Comment: {{.Comment}}</span>{{end}}
      <form method="post" action="/suggest/alias/delete">
        <input type="hidden" name="username" value="{{.Username}}">
        <input type="hidden" name="id" value="{{.ID}}">
        <input type="submit" value="Delete">
      </form>
      <div class="alias-body">
	<span class="alias-span">{{.Old}} &rarr; {{.New}}</span>
	{{if .Comment}}<span class="alias-span">Comment: {{.Comment}}</span>{{end}}
        <div class="alias-body-field alias-body-field-tag">
          <label for="old">Old Tag:</label>
          <input id="old" type="text" name="old" value="{{.Old}}" readonly>
	</div>
        <div class="alias-body-field alias-body-field-tag">
          <label for="new">New Tag:</label>
          <input id="new" type="text" name="new" value="{{.New}}" readonly>
	</div>
        <div class="alias-body-field alias-body-field-comment">
          <label for="comment">Comment:</label>
          <input id="comment" type="text" name="comment" value="{{.Comment}}" readonly>
	</div>
        <div class="alias-body-field alias-body-field-comment">
          <label for="explanation">Explanation:</label>
          <input id="explanation" type="text" name="comment" value="{{.Comment}}" readonly>
	</div>
      </div>
    </div>
  {{ end }}
{{ end }}
`
	baseTemplate = `
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>suggest</title>
	<script type='text/javascript'>
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', '{{.Conf.AnalyticsID}}']);
		_gaq.push(['_trackPageview']);
		(function() {
		  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
	</script>
	<meta name="description" content="{{.Conf.Description}}">
	<meta name="keywords" content="{{.Conf.Keywords}}">
	<style>
		* {
			font-size: 16px;
			line-height: 1.2;
			font-family: Verdana, Geneva, sans-serif;
		}
		a:link {
			color:#006FFA;
			text-decoration:none;
		}
		a:visited {
			color:#006FFA;
			text-decoration:none;
		}
		a:hover {
			color:#33CFFF;
			text-decoration:none;
		}
		a:active {
			color:#006FFA;
			text-decoration:none;
		}

		p, a, span {font-size: 120%;}

		body {
			list-style-type: none;
			padding-top: 0;
			margin-top: 0;
		}

		#site-title {
			font-size: 133%;
			padding: 0.5em;
			margin: 0;
		}

		#subnav {
		    background: #f6f6f6;
			padding-top: 1em;
			padding-bottom: 1em;
			border-top: 1px #ebebeb solid;
			border-bottom: 1px #ebebeb solid;
		}

		#subnav a {
		    padding: 0.5em;
		}

		#subnav subnav-button-link {
		    padding: 0.5em;
		}

		.subnav-button-form {
			display: inline;
		}

		.subnav-button-link {
			background: none!important;
			border: none;
			padding: 0!important;
			font: inherit;
			font-size: 120%;
			cursor: pointer;
			color: #006FFA;
			display: inline;
		}

		.subnav-button-link:visited {
			color:#006FFA;
			text-decoration:none;
		}
		.subnav-button-link:hover {
			color:#33CFFF;
			text-decoration:none;
		}
		.subnav-button-link:active {
			color:#006FFA;
			text-decoration:none;
		}

		#login-form label, #login-form input, #login-form button, #login-form em {
			padding: 0.5em;
			display: block;
			font-size: 120%;
			line-height:1.2;
		}

		#login-form button {
			margin-top: 0.5em;
		}

		#login-form h1 {
			padding: 0.5em;
			font-size: 120%;
		}

		.toolbar {
			padding: 0.5em;
		}
		.toolbar input, .toolbar button {
			font-size: 120%;
		}

		.suggestion {
			padding: 0.5em;
			border-top: 1px #ebebeb solid;
			border-bottom: 1px #ebebeb solid;
			border-left: 0.3em #006FFA solid;
			border-top-left-radius: 0.3em;
			border-bottom-left-radius: 0.3em;
			line-height: 200%;
		}

		.suggestion form {
			display: inline;
		}

		.suggestion textarea {
			display: block;
			font-size: 120%;
			line-height:1.2;
		}
		.suggestion:nth-of-type(even) {
		    background: #f6f6f6;
		}

		.suggestion-form {
			padding: 0.5em;
			line-height: 200%;
		}

		textarea {
			width: 70%;
		}
		@media (max-width: 768px) {
			textarea {
				width: 100%;
			}
		}

		.suggestion-form input[type=submit] {
			padding: 0.5em;
			margin-top: 0.5em;
			display: block;
		}

		.alert {
			border-radius: 4px;
			padding: 1em;
			margin-top: 0.5em;
			margin-bottom: 0.5em;
			font-size: 120%;
			width: 70%;
		}
		.alert strong {
			font-size: inherit;
		}
		@media (max-width: 768px) {
			.alert{
				width: 90%;
				padding-left:5%;
				padding-right:5%;
			}
		}

		.alert-success {
			color: #3c763d;
			background-color: #dff0d8;
			border-color: #d6e9c6;
		}

		.alert-error {
			color: #a94442;
			background-color: #f2dede;
			border-color: #ebccd1;
		}

		footer {
			color: #ccc;
			font-size: 0.9em;
			padding-left: 0.5em;
			padding-top: 1em;
		}

		footer a {
			font-size: 0.9em;
		}

	</style>
	{{block "css" .}}{{end}}
</head>
<body>
	<h1 id="site-title"><a href="/post/list">{{.Conf.SiteTitle}}</a></h1>
	{{block "subnav" .}}{{end}}
	{{block "toolbar" .}}{{end}}
	{{block "content" .}}{{end}}
	<footer>
		{{block "footer" .}}{{end}}
		<em>Served by <a href="https://github.com/kusubooru/teian">teian</a> v{{.Conf.Version}}</em>
	</footer>
</body>
</html>

`
	loginTemplate = `
{{define "content"}}
<form id="login-form" method="post" action="/suggest/login/submit">
<h1>Login</h1>
    <label for="username">User name</label>
    <input type="text" id="username" name="username">
    <label for="password">Password</label>
    <input type="password" id="password" name="password">
    <button type="submit">Login</button>
	{{if .Data}}
	<em>{{.Data}}</em>
	{{end}}
</form>
{{end}}
`
	navTemplate = `
{{define "subnav"}}
<div id="subnav">
	<a href="/suggest">New suggestion</a>
	<a href="/suggest/alias">Suggested alias</a>
	<form class="subnav-button-form" method="post" action="/suggest/logout">
	     <input class="subnav-button-link" type="submit" value="Logout">
	</form>
</div>
{{end}}
`
	submitTemplate = `
{{define "content"}}
{{ if .Data.Err }}
<!-- Error -->
<!-- .Data.Err  -->
<!--  -->
{{end}}
{{ if .Data.Msg }}
<div class="alert alert-{{.Data.Type}}">
	<strong>
	{{if eq .Data.Type "success"}}
	Success:
	{{else}}
	Error:
	{{end}}
	</strong>{{.Data.Msg}}
</div>
{{end}}
{{end}}
`
	suggestionTemplate = `
{{define "content"}}
<div class="suggestion-form">
	<form method="post" action="/suggest/submit">
		<p>{{.Conf.WriteMsg}}</p>
		<textarea class="large" rows="20" cols="80" name="text" placeholder="Write your suggestion here."></textarea>
		<input type="submit">
	</form>
</div>
{{end}}
`
	toolbarTemplate = `
{{define "toolbar"}}
<div class="toolbar">
	<form method="get" action="/suggest/admin">
		<input type="text" name="u" placeholder="Username">
		<input type="text" name="t" placeholder="Text">
		<label for="order">Order By</label>
		<select id="order" name="o">
			<option value="dd">Date Desc</option>
			<option value="da">Date Asc</option>
			<option value="ud">Username Desc</option>
			<option value="ua">Username Asc</option>
		</select>
	    <button type="submit">Search</button>
		<input type="reset" value="Reset">
	</form>
</div>
{{end}}
`
)
